Add missing UnitSystem to variant and EOSPAC
lanl/singularity-eos pull request #265
Opened 2023-07-06 07:35 UTC by rbberger

## PR Summary

- rewrites how variant type lists for Relativistic and UnitSystem are created, adding missing combinations
- also allows EOSPAC to make use of it
- add unit test for UnitSystem<EOSPAC>

@Yurlungur please take a closer look at what I had to do in `SpecificHeatFromDensityTemperature` to keep the scalar and vector functions consistent.

## PR Checklist

- [ ] Adds a test for any bugs fixed. Adds tests for new features.
- [ ] Format your changes by using the `make format` command after configuring with `cmake`.
- [ ] Document any new features, update documentation for changes made.
- [ ] Make sure the copyright notice on any files you modified is up to date.
- [ ] After creating a pull request, note it in the CHANGELOG.md file
- [ ] If preparing for a new release, update the version in cmake.

2023-07-06 14:12 UTC, Yurlungur requested changes
Overall looks good. Looks like the python bindings test is failing, though. Also you're missing a changelog. ;)

2023-07-06 14:12 UTC, Yurlungur commented on singularity-eos/eos/eos_eospac.hpp
> +              cvFromSesame(std::max(DEDT[i], 0.0)); // Here we do something to the data!
Either way I think we don't put the onus on this PR to change things if we decide to do that. We leave it for a later MR.

2023-07-06 16:14 UTC, rbberger commented on singularity-eos/eos/eos.hpp
> +template <template <typename> class... Ts>
No, up to C++14 this is what was supported. Starting with C++17 you can write `typename...` here. Clang gives you a C++17 usage warning here.

2023-07-06 16:19 UTC, rbberger commented on singularity-eos/eos/eos.hpp
> +template <template <typename> class... Ts>
See https://en.cppreference.com/w/cpp/language/parameter_pack

2023-07-06 16:37 UTC, Yurlungur commented on singularity-eos/eos/eos.hpp
> +template <template <typename> class... Ts>
Huh. Good to know. I thought they were equivalent.

2023-07-06 17:31 UTC, dholladay00 commented on singularity-eos/eos/eos.hpp
> +template <template <typename> class... Ts>
I think xl also gave a warning there, in my mr #245 it has this change as well.

2023-07-06 18:01 UTC, rbberger commented
@Yurlungur Added the CHANGELOG.md and fixed the Python bindings.

2023-07-12 20:54 UTC, Yurlungur approved these changes

2023-08-09 20:37 UTC, mauneyc-LANL commented on singularity-eos/eos/eos_eospac.hpp
> +              cvFromSesame(std::max(DEDT[i], 0.0)); // Here we do something to the data!
@Yurlungur see this from meeting

2023-08-09 23:20 UTC, Yurlungur commented
Submitted tests to re-git. When they pass let's get this in.

2023-08-23 22:51 UTC, merged